services:
  backend:
    build:
      args:
        PROJECT_DIR: brand_new
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./volume:/src/
version: '3.8'
