version: "1"
services:
  backend:
    build: 
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app  
    command: bash -c "poetry install && poetry run python -m df_designer run-app --ip-address 0.0.0.0 --port 8000"
  frontend:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
      - REACT_APP_BACKEND_URL=http://backend:8000
      - REACT_APP_BACKEND_WS_URL=ws://backend:8000
    ports:
      - 3000:3000
    environment:
      - VITE_PROXY_TARGET=http://backend:8000
    volumes:
      - ./df_designer_front:/app/df_designer_front
    command: bash -c "cd ./df_designer_front && npm install && npm start"