name: build_and_publish_docs
on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    name: build and publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry install --with dev --no-interaction
        working-directory: backend

      - name: build api documentation
        run: make build_api_docs

      - name: remove jekyll theming for api
        run: touch docs/_build/html/.nojekyll

      - name: setup Bun
        run: npm install -g bun

      - name: install ui docs dependencies
        run: bun install
        working-directory: docs/ui-docs

      - name: build ui documentation
        run: bun run build
        working-directory: docs/ui-docs

      - name: remove jekyll theming for ui
        run: touch docs/ui-docs/out/.nojekyll

      - name: deploy api documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html
          target-folder: api
          single-commit: True

      - name: deploy frontend documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/ui-docs/out
          target-folder: ui
          single-commit: True
