name: Build Docker Images

on:
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup poetry and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m poetry lock --no-update
          python -m poetry install --with lint --no-ansi --no-interaction
        working-directory: backend

      - name: Create new project
        run: python -m poetry run chatsky.ui init --destination ../../ --no-input --overwrite-if-exists
        working-directory: backend

      - name: Build Frontend
        run: docker build -f Dockerfile --build-arg PROJECT_DIR=df_designer_project --target=frontend-builder .

      - name: Build backend & run app
        run: docker build -f Dockerfile --build-arg PROJECT_DIR=df_designer_project --target=runtime .
