name: front check

on: [push, pull_request]

jobs:
  build_and_check_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Build frontend
        run: bun run build
        working-directory: frontend
